#!/usr/bin/env bash
# installs nginx to my serve

echo -e "Updat8ng and installing nginx\n"
sudo apt-get -y update -qq && \
	     sudo apt-get -y install nginx
echo -e "\nsetting up some config\n"
sudo service nginx start
# allow8ng nginx on firewall
sudo ufw allow "Nginx HTTP"

# giving user ownership and permision to edit files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" | dd  status=none of=/var/www/html/index.nginx-debian.html

sudo service nginx restart

echo -e "\n completed....\n"
